export const LOGIN_TEXTS = {
    title : "Bienvenido a la WebAPP",
    description : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ullamcorper nisl erat, vel convallis elit fermentum pellentesque. Sed mollis velit facilisis facilisis viverra.",
    loginTitle : "Ingresa con tu Cuenta",
    loginDescription : "Ingrese sus Credenciales para poder Iniciar Sesión",
    btnLoginOn : "Ingresar",
    registerTitle : "Crea Cuenta",
    registerDescription : "Complete el formulario para crear una cuenta",
    createAccount : "Crear una Cuenta",
    DontHaveAccount : "¿No tienes una Cuenta?",
    usernamePlaceholder : "Email",
    passwordPlaceholder : "Contraseña",
    remember : "Recordar",
    forgotPassword : "¿Ha Olvidado su Contraseña?",
    registerPlaceholderInput1 : "Nombre",
    registerPlaceholderInput2 : "Email",
    registerPlaceholderInput3 : "Contraseña",
    registerPlaceholderInput4 : "Contraseña (Confirmar)",
    btnCreateAccount : "Crear mi Cuenta",
    readyLogin : "¿Ya tienes una cuenta?",
    readyLoginLink : "Ingresar"
}
